version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret

  laravel:
    image: php:8.2-fpm
    container_name: laravel-backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html

  frontend:
    image: node:18-alpine
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app