version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret

  symfony:
    image: php:8.2-apache
    container_name: symfony
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html:rw
    depends_on:
      - postgres
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y libpq-dev &&
      docker-php-ext-install pdo pdo_pgsql &&
      sed -i 's#DocumentRoot /var/www/html#DocumentRoot /var/www/html/public#g' /etc/apache2/sites-available/000-default.conf &&
      echo '<Directory /var/www/html/public>' >> /etc/apache2/sites-available/000-default.conf &&
      echo '  AllowOverride All' >> /etc/apache2/sites-available/000-default.conf &&
      echo '  Require all granted' >> /etc/apache2/sites-available/000-default.conf &&
      echo '</Directory>' >> /etc/apache2/sites-available/000-default.conf &&
      a2enmod rewrite &&
      apache2-foreground"

  frontend:
    image: node:18-alpine
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      sh -c "
      npm install &&
      npm start"